-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 19:14:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema datawarehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `datawarehouse` ;

-- -----------------------------------------------------
-- Schema datawarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datawarehouse` DEFAULT CHARACTER SET utf8 ;
USE `datawarehouse` ;

-- -----------------------------------------------------
-- Table `datawarehouse`.`PAISES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`PAISES` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`PAISES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`CALENDARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`CALENDARIO` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`CALENDARIO` (
  `data` DATE NOT NULL,
  PRIMARY KEY (`data`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`COVID_JHONS_HOPKINS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`COVID_JHONS_HOPKINS` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`COVID_JHONS_HOPKINS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `CALENDARIO_data` DATE NOT NULL,
  `confirmados` INT NULL,
  `mortes` INT NULL,
  `recuperados` INT NULL,
  `novos_casos` INT NULL,
  `novas_mortes` INT NULL,
  `ativos` INT NULL,
  INDEX `fk_TABELA_FATO_PAISES_idx` (`PAISES_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  INDEX `fk_COVID_JHONS_HOPKINS_CALENDARIO1_idx` (`CALENDARIO_data` ASC) VISIBLE,
  CONSTRAINT `fk_TABELA_FATO_PAISES`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COVID_JHONS_HOPKINS_CALENDARIO1`
    FOREIGN KEY (`CALENDARIO_data`)
    REFERENCES `datawarehouse`.`CALENDARIO` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`RANK_FELICIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`RANK_FELICIDADE` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`RANK_FELICIDADE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `ano` INT NULL,
  `periodo_referencia` VARCHAR(45) NULL,
  `nota` DOUBLE NULL,
  `classificacao` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_NOTA_FELICIDADE_PAISES1_idx` (`PAISES_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_FELICIDADE_PAISES1`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`LOCKDOWNS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`LOCKDOWNS` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`LOCKDOWNS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `total_dias` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_LOCKDOWNS_PAISES1_idx` (`PAISES_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LOCKDOWNS_PAISES1`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`SENTIMENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`SENTIMENTOS` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`SENTIMENTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `CALENDARIO_data` DATE NOT NULL,
  `tweet` LONGTEXT NULL,
  `negativo` DOUBLE NULL,
  `positivo` DOUBLE NULL,
  `neutro` DOUBLE NULL,
  `composto` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_SENTIMENTOS_PAISES1_idx` (`PAISES_ID` ASC) VISIBLE,
  INDEX `fk_SENTIMENTOS_CALENDARIO1_idx` (`CALENDARIO_data` ASC) VISIBLE,
  CONSTRAINT `fk_SENTIMENTOS_PAISES1`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SENTIMENTOS_CALENDARIO1`
    FOREIGN KEY (`CALENDARIO_data`)
    REFERENCES `datawarehouse`.`CALENDARIO` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`DEMANDA_ENERGIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`DEMANDA_ENERGIA` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`DEMANDA_ENERGIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `CALENDARIO_data` DATE NOT NULL,
  `demanda_TWh` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DEMANDA_ENERGIA_PAISES1_idx` (`PAISES_ID` ASC) VISIBLE,
  INDEX `fk_DEMANDA_ENERGIA_CALENDARIO1_idx` (`CALENDARIO_data` ASC) VISIBLE,
  CONSTRAINT `fk_DEMANDA_ENERGIA_PAISES1`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEMANDA_ENERGIA_CALENDARIO1`
    FOREIGN KEY (`CALENDARIO_data`)
    REFERENCES `datawarehouse`.`CALENDARIO` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`PREVISAO_CASOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`PREVISAO_CASOS` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`PREVISAO_CASOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `CALENDARIO_data` DATE NOT NULL,
  `data_prevista` DATE NULL,
  `casos_previstos` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PREVISAO_CASOS_PAISES1_idx` (`PAISES_ID` ASC) VISIBLE,
  INDEX `fk_PREVISAO_CASOS_CALENDARIO1_idx` (`CALENDARIO_data` ASC) VISIBLE,
  CONSTRAINT `fk_PREVISAO_CASOS_PAISES1`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PREVISAO_CASOS_CALENDARIO1`
    FOREIGN KEY (`CALENDARIO_data`)
    REFERENCES `datawarehouse`.`CALENDARIO` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datawarehouse`.`COVID_WORLDOMETER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawarehouse`.`COVID_WORLDOMETER` ;

CREATE TABLE IF NOT EXISTS `datawarehouse`.`COVID_WORLDOMETER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAISES_ID` INT NOT NULL,
  `CALENDARIO_data` DATE NOT NULL,
  `populacao` INT NULL,
  `total_casos` INT NULL,
  `novos_casos` INT NULL,
  `total_mortes` INT NULL,
  `novas_mortes` INT NULL,
  `total_recuperados` INT NULL,
  `novos_recuperados` INT NULL,
  `casos_ativos` INT NULL,
  `casos_criticos` INT NULL,
  `total_casos_1Mpop` DOUBLE NULL,
  `total_mortes_1Mpop` DOUBLE NULL,
  `total_testes` INT NULL,
  `total_testes_1Mpop` DOUBLE NULL,
  `mortalidade` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_COVID_WORLDMETER_PAISES1_idx` (`PAISES_ID` ASC) VISIBLE,
  INDEX `fk_COVID_WORLDOMETER_CALENDARIO1_idx` (`CALENDARIO_data` ASC) VISIBLE,
  CONSTRAINT `fk_COVID_WORLDMETER_PAISES1`
    FOREIGN KEY (`PAISES_ID`)
    REFERENCES `datawarehouse`.`PAISES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COVID_WORLDOMETER_CALENDARIO1`
    FOREIGN KEY (`CALENDARIO_data`)
    REFERENCES `datawarehouse`.`CALENDARIO` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
